-- Create fiscal_sponsors table
CREATE TABLE IF NOT EXISTS fiscal_sponsors (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  location text NOT NULL,
  city text,
  state text,
  focus_areas text[] DEFAULT ARRAY[]::text[],
  fee_range text,
  website_url text,
  description text,
  source text DEFAULT 'fiscalsponsordirectory.org',
  is_active boolean DEFAULT true,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_fiscal_sponsors_state ON fiscal_sponsors(state);
CREATE INDEX IF NOT EXISTS idx_fiscal_sponsors_focus_areas ON fiscal_sponsors USING gin(focus_areas);
CREATE INDEX IF NOT EXISTS idx_fiscal_sponsors_active ON fiscal_sponsors(is_active) WHERE is_active = true;
CREATE INDEX IF NOT EXISTS idx_fiscal_sponsors_search ON fiscal_sponsors USING gin(
  to_tsvector('english', coalesce(name, '') || ' ' || coalesce(description, '') || ' ' || coalesce(location, ''))
);

-- Enable RLS
ALTER TABLE fiscal_sponsors ENABLE ROW LEVEL SECURITY;

-- Allow all authenticated users to read
CREATE POLICY "Anyone can view active fiscal sponsors" 
  ON fiscal_sponsors FOR SELECT 
  USING (is_active = true);

-- Only admins can modify (via service role)
CREATE POLICY "Only admins can modify fiscal sponsors" 
  ON fiscal_sponsors FOR ALL 
  USING (false);

-- Insert all 401 fiscal sponsors from FiscalSponsorDirectory.org
INSERT INTO fiscal_sponsors (name, location, city, state, focus_areas, description) VALUES
('1st Note Music Foundation', 'Denver, CO', 'Denver', 'CO', ARRAY['Arts', 'Music'], 'Music education and arts programs'),
('50CAN, Inc.', 'Washington, D.C.', 'Washington', 'DC', ARRAY['Education'], 'Education reform advocacy'),
('95 Counties Tennessee', 'Nashville, TN', 'Nashville', 'TN', ARRAY['Community Development'], 'Statewide community initiatives'),
('The Abundance Foundation', 'Pittsboro, NC', 'Pittsboro', 'NC', ARRAY['Community Development'], 'Community-based projects'),
('Accessible Festivals', 'Stockton, NJ', 'Stockton', 'NJ', ARRAY['Arts', 'Accessibility'], 'Making festivals accessible'),
('Afram Global Organization Inc.', 'Bellflower, CA', 'Bellflower', 'CA', ARRAY['Social Justice', 'International'], 'African diaspora initiatives'),
('African Voices Communications, Inc.', 'New York, NY', 'New York', 'NY', ARRAY['Media', 'Social Justice'], 'African perspectives in media'),
('AfroPresencia', 'Brooklyn, NY', 'Brooklyn', 'NY', ARRAY['Arts', 'Culture', 'BIPOC'], 'Afro-Latino arts and culture'),
('A God Send', 'Orange Park, FL', 'Orange Park', 'FL', ARRAY['Community Development'], 'Community service projects'),
('AIDS Connecticut (ACT)', 'Hartford, CT', 'Hartford', 'CT', ARRAY['Health', 'HIV/AIDS'], 'HIV/AIDS services and advocacy'),
('AJ Muste Memorial Institute', 'New York, NY', 'New York', 'NY', ARRAY['Social Justice', 'Peace'], 'Peace and social justice activism'),
('Alliance for Global Justice', 'Tucson, AZ', 'Tucson', 'AZ', ARRAY['Social Justice', 'International'], 'Global justice movements'),
('Allied Arts Foundation', 'Seattle, WA', 'Seattle', 'WA', ARRAY['Arts', 'Culture'], 'Arts advocacy in Seattle'),
('Alternative Newsweekly Foundation', 'Washington, D.C.', 'Washington', 'DC', ARRAY['Media', 'Journalism'], 'Independent journalism support'),
('American Muslim Community Foundation', 'Fremont, CA', 'Fremont', 'CA', ARRAY['Community Development', 'Faith'], 'Muslim community initiatives'),
('Angels for Angels', 'Seattle, WA', 'Seattle', 'WA', ARRAY['Community Development'], 'Community support programs'),
('Another Choice, Another Chance', 'Sacramento, CA', 'Sacramento', 'CA', ARRAY['Social Justice'], 'Reentry and rehabilitation'),
('Apereo Foundation', 'Beaverton, OR', 'Beaverton', 'OR', ARRAY['Education', 'Tech'], 'Open source education software'),
('Art of the Matter', 'San Francisco, CA', 'San Francisco', 'CA', ARRAY['Arts'], 'Arts advocacy'),
('Artportunity Knocks', 'Atlanta, GA', 'Atlanta', 'GA', ARRAY['Arts', 'Youth'], 'Youth arts programs'),
('Artrain', 'Ann Arbor, MI', 'Ann Arbor', 'MI', ARRAY['Arts', 'Education'], 'Mobile arts museum'),
('Arts Alive! Inc.', 'Keene, NH', 'Keene', 'NH', ARRAY['Arts', 'Culture'], 'Regional arts support'),
('Arts & Business Council of Greater Nashville', 'Nashville, TN', 'Nashville', 'TN', ARRAY['Arts', 'Business'], 'Arts-business partnerships'),
('Arts Services Inc.', 'Buffalo, NY', 'Buffalo', 'NY', ARRAY['Arts'], 'Arts administration services'),
('Assembly for the Arts', 'Cleveland, OH', 'Cleveland', 'OH', ARRAY['Arts'], 'Arts advocacy Cleveland'),
('Association Building Community', 'Oakland, CA', 'Oakland', 'CA', ARRAY['Community Development'], 'Community organizing'),
('Association of Independents in Radio', 'New York, NY', 'New York', 'NY', ARRAY['Media', 'Audio'], 'Independent radio producers'),
('Austin Creative Alliance', 'Austin, TX', 'Austin', 'TX', ARRAY['Arts'], 'Austin arts community'),
('Austin Film Society', 'Austin, TX', 'Austin', 'TX', ARRAY['Film', 'Media'], 'Film culture and education'),
('Baltimore Civic Fund', 'Baltimore, MD', 'Baltimore', 'MD', ARRAY['Civic Engagement'], 'Civic projects Baltimore'),
('BASICS', 'Milwaukee, WI', 'Milwaukee', 'WI', ARRAY['Community Development'], 'Community initiatives'),
('Bay Area Video Coalition', 'San Francisco, CA', 'San Francisco', 'CA', ARRAY['Film', 'Media'], 'Media arts and education'),
('BE Meditation Group', 'Los Angeles, CA', 'Los Angeles', 'CA', ARRAY['Wellness', 'Spirituality'], 'Meditation and mindfulness'),
('Bmore Empowered Inc.', 'Baltimore, MD', 'Baltimore', 'MD', ARRAY['Community Development'], 'Baltimore empowerment'),
('Berkeley Art Center', 'Berkeley, CA', 'Berkeley', 'CA', ARRAY['Arts'], 'Visual arts center'),
('Berkeley Partners for Parks', 'Berkeley, CA', 'Berkeley', 'CA', ARRAY['Environment', 'Parks'], 'Parks improvement'),
('Betty Jean Brown Foundation', 'Lafayette, CA', 'Lafayette', 'CA', ARRAY['Community Development'], 'Community support'),
('The Big Picture Film and Video Foundation', 'Atlanta, GA', 'Atlanta', 'GA', ARRAY['Film', 'Documentary'], 'Documentary film support'),
('Billings Community Foundation', 'Billings, MT', 'Billings', 'MT', ARRAY['Community Development'], 'Montana community grants'),
('The Biodiversity Group', 'Tucson, AZ', 'Tucson', 'AZ', ARRAY['Environment', 'Conservation'], 'Biodiversity conservation'),
('Blue Earth Alliance', 'Seattle, WA', 'Seattle', 'WA', ARRAY['Photography', 'Environment'], 'Environmental photography'),
('Boise Film Foundation', 'Boise, ID', 'Boise', 'ID', ARRAY['Film'], 'Film community Boise'),
('Boston Dance Alliance', 'Boston, MA', 'Boston', 'MA', ARRAY['Arts', 'Dance'], 'Dance community support'),
('Boulder County Arts Alliance', 'Boulder, CO', 'Boulder', 'CO', ARRAY['Arts'], 'Arts advocacy Boulder'),
('Brooklyn Arts Council', 'Brooklyn, NY', 'Brooklyn', 'NY', ARRAY['Arts'], 'Brooklyn arts support'),
('Brown Girl Wellness, Inc.', 'Baltimore, MD', 'Baltimore', 'MD', ARRAY['Health', 'Women', 'BIPOC'], 'BIPOC women wellness'),
('Buddhist Film Foundation, Inc.', 'Berkeley, CA', 'Berkeley', 'CA', ARRAY['Film', 'Spirituality'], 'Buddhist-themed films'),
('Build Missouri Health', 'St. Louis, MO', 'St. Louis', 'MO', ARRAY['Health'], 'Health initiatives Missouri'),
('Build Up, Inc.', 'New York, NY', 'New York', 'NY', ARRAY['Community Development'], 'Community building'),
('The Carla Rose Foundation, Inc.', 'Spartanburg, SC', 'Spartanburg', 'SC', ARRAY['Community Development'], 'Community support'),
('CascadiaNow!', 'Seattle, WA', 'Seattle', 'WA', ARRAY['Environment', 'Bioregionalism'], 'Cascadia bioregion'),
('Center for Community Stewardship', 'Madison, WI', 'Madison', 'WI', ARRAY['Community Development'], 'Community leadership'),
('Center for Independent Documentary Inc.', 'Boston, MA', 'Boston', 'MA', ARRAY['Film', 'Documentary'], 'Documentary filmmaking'),
('Center for Social Change', 'Miami, FL', 'Miami', 'FL', ARRAY['Social Justice'], 'Social change initiatives'),
('Center for Transformative Action', 'Ithaca, NY', 'Ithaca', 'NY', ARRAY['Social Justice'], 'Transformative justice'),
('Center for Volunteer and Nonprofit Leadership', 'San Rafael, CA', 'San Rafael', 'CA', ARRAY['Nonprofit Support'], 'Nonprofit capacity building'),
('CENTER Santa Fe', 'Santa Fe, NM', 'Santa Fe', 'NM', ARRAY['Arts'], 'Contemporary arts'),
('Chabot-Las Positas Community College District', 'Pleasanton, CA', 'Pleasanton', 'CA', ARRAY['Education'], 'Community college district'),
('The Chainges Fund, Inc.', 'Atlanta, GA', 'Atlanta', 'GA', ARRAY['Community Development'], 'Community change'),
('Chalice Oak Foundation', 'Rancho Palos Verdes, CA', 'Rancho Palos Verdes', 'CA', ARRAY['Spirituality', 'Community Development'], 'Spiritual community'),
('Chappy & Friends', 'Chicago, IL', 'Chicago', 'IL', ARRAY['Community Development'], 'Community programs'),
('Charitable Ventures', 'Santa Ana, CA', 'Santa Ana', 'CA', ARRAY['Nonprofit Support'], 'Fiscal sponsorship services'),
('Charity Music, Inc', 'Sterling Heights, MI', 'Sterling Heights', 'MI', ARRAY['Arts', 'Music'], 'Music for charity'),
('CHC: Creating Healthier Communities', 'Alexandria, VA', 'Alexandria', 'VA', ARRAY['Health'], 'Health equity'),
('Chicago Filmmakers', 'Chicago, IL', 'Chicago', 'IL', ARRAY['Film'], 'Independent film Chicago'),
('Children\'s Network of Solano County', 'Fairfield, CA', 'Fairfield', 'CA', ARRAY['Children', 'Youth'], 'Children services'),
('City Embrace Counseling Center', 'San Francisco, CA', 'San Francisco', 'CA', ARRAY['Health', 'Mental Health'], 'Mental health services'),
('City Lore', 'New York, NY', 'New York', 'NY', ARRAY['Arts', 'Culture'], 'Urban folk culture'),
('Clearwater Resource Conservation and Development Council, Inc.', 'Moscow, ID', 'Moscow', 'ID', ARRAY['Environment', 'Conservation'], 'Natural resource conservation'),
('Cloud Forest Institute', 'Ukiah, CA', 'Ukiah', 'CA', ARRAY['Environment'], 'Forest conservation'),
('Colorado Nonprofit Development Center', 'Denver, CO', 'Denver', 'CO', ARRAY['Nonprofit Support'], 'Nonprofit development'),
('Columbia Basin Foundation', 'Ephrata, WA', 'Ephrata', 'WA', ARRAY['Community Development'], 'Regional development'),
('Communities Foundation of Oklahoma', 'Oklahoma City, OK', 'Oklahoma City', 'OK', ARRAY['Community Development'], 'Oklahoma communities'),
('Community2gether Inc.', 'Warwick, NY', 'Warwick', 'NY', ARRAY['Community Development'], 'Community connection'),
('Community Capital Fund', 'Kansas City, MO', 'Kansas City', 'MO', ARRAY['Economic Development'], 'Community finance'),
('Community Coordinated Child Care (4-C)', 'Madison, WI', 'Madison', 'WI', ARRAY['Children', 'Education'], 'Childcare coordination'),
('Community Foundation for the National Capital Region', 'Washington, D.C.', 'Washington', 'DC', ARRAY['Community Development'], 'DC area philanthropy'),
('Community Foundation of Brazoria County', 'Angleton, TX', 'Angleton', 'TX', ARRAY['Community Development'], 'Texas county foundation'),
('Community Initiatives', 'Oakland, CA', 'Oakland', 'CA', ARRAY['Social Justice', 'Community Development'], 'Grassroots organizing support'),
('Community LIFT', 'Memphis, TN', 'Memphis', 'TN', ARRAY['Community Development'], 'Memphis community'),
('Community Partners', 'Los Angeles, CA', 'Los Angeles', 'CA', ARRAY['Nonprofit Support'], 'Major fiscal sponsor'),
('Community Shares Tennessee', 'Knoxville, TN', 'Knoxville', 'TN', ARRAY['Nonprofit Support'], 'Workplace giving'),
('Conscious Goodness', 'Santa Monica, CA', 'Santa Monica', 'CA', ARRAY['Spirituality', 'Wellness'], 'Conscious living'),
('CORE Foundation Inc.', 'Reston, VA', 'Reston', 'VA', ARRAY['Community Development'], 'Community organizing'),
('Corry Community Development Corporation', 'Corry, PA', 'Corry', 'PA', ARRAY['Community Development'], 'Rural development'),
('CORE Community Organized Relief Effort', 'Los Angeles, CA', 'Los Angeles', 'CA', ARRAY['Emergency Relief', 'Community Development'], 'Disaster relief'),
('Create Wisconsin', 'Madison, WI', 'Madison', 'WI', ARRAY['Arts'], 'Wisconsin arts advocacy'),
('Creative Many Michigan', 'Detroit, MI', 'Detroit', 'MI', ARRAY['Arts'], 'Michigan creative sector'),
('Creative Visions', 'Malibu, CA', 'Malibu', 'CA', ARRAY['Film', 'Social Justice'], 'Media for social change'),
('CultureWorks Greater Philadelphia', 'Philadelphia, PA', 'Philadelphia', 'PA', ARRAY['Arts', 'Nonprofit Support'], 'Arts organization support'),
('Dalit Solidarity', 'San Diego, CA', 'San Diego', 'CA', ARRAY['Social Justice', 'International'], 'Dalit rights'),
('Dance Films Association', 'Brooklyn, NY', 'Brooklyn', 'NY', ARRAY['Dance', 'Film'], 'Dance on film'),
('Dance Resource Center', 'Los Angeles, CA', 'Los Angeles', 'CA', ARRAY['Dance'], 'Dance community LA'),
('Dancers\' Group', 'San Francisco, CA', 'San Francisco', 'CA', ARRAY['Dance'], 'Dance community SF'),
('DAS Foundation Inc.', 'Phoenix, AZ', 'Phoenix', 'AZ', ARRAY['Community Development'], 'Community support'),
('Daylight Community Arts Foundation', 'Bronx, NY', 'Bronx', 'NY', ARRAY['Arts', 'Community Development'], 'Bronx arts'),
('Del Mar Foundation', 'Del Mar, CA', 'Del Mar', 'CA', ARRAY['Community Development'], 'Community grants'),
('Del Valle Community Coalition Non-Profit', 'Austin, TX', 'Austin', 'TX', ARRAY['Community Development'], 'Austin community'),
('Denver Film', 'Denver, CO', 'Denver', 'CO', ARRAY['Film'], 'Film community Denver'),
('Department of Bioregion', 'Seattle, WA', 'Seattle', 'WA', ARRAY['Environment', 'Bioregionalism'], 'Bioregional organizing'),
('Discover Your Northwest', 'Seattle, WA', 'Seattle', 'WA', ARRAY['Environment', 'Education'], 'Public lands education'),
('Docs In Progress', 'Silver Spring, MD', 'Silver Spring', 'MD', ARRAY['Film', 'Documentary'], 'Documentary workshops'),
('Documentary Educational Resources', 'Watertown, MA', 'Watertown', 'MA', ARRAY['Film', 'Documentary', 'Education'], 'Documentary distribution'),
('Earth Island Institute', 'Berkeley, CA', 'Berkeley', 'CA', ARRAY['Environment'], 'Environmental projects incubator'),
('EarthShare', 'Washington, D.C.', 'Washington', 'DC', ARRAY['Environment'], 'Environmental workplace giving'),
('East Bay Asian Local Development Corporation', 'Oakland, CA', 'Oakland', 'CA', ARRAY['Community Development', 'Asian American'], 'AAPI community development'),
('Ecologistics Inc.', 'Los Osos, CA', 'Los Osos', 'CA', ARRAY['Environment'], 'Ecological logistics'),
('Economic Empowerment Foundation for Exempt Startups & Small Businesses (EEF-501c)™', 'Bowie, MD', 'Bowie', 'MD', ARRAY['Economic Development', 'Small Business'], 'Small business support'),
('Education Consortium of Central Los Angeles', 'Los Angeles, CA', 'Los Angeles', 'CA', ARRAY['Education'], 'LA education'),
('Educational Media Foundation, Inc.', 'Richmond Hill, GA', 'Richmond Hill', 'GA', ARRAY['Media', 'Education'], 'Educational media'),
('Edward Charles Foundation', 'Beverly Hills, CA', 'Beverly Hills', 'CA', ARRAY['Community Development'], 'Community grants'),
('Embolden WI', 'Madison, WI', 'Madison', 'WI', ARRAY['Community Development'], 'Wisconsin empowerment'),
('Empower Me', 'Roebuck, SC', 'Roebuck', 'SC', ARRAY['Community Development'], 'Empowerment programs'),
('Empowerment Works', 'Oakland, CA', 'Oakland', 'CA', ARRAY['Community Development'], 'Community empowerment'),
('Evergreen Social Impact', 'Bothell, WA', 'Bothell', 'WA', ARRAY['Social Impact'], 'Social impact initiatives'),
('EveryLibrary Institute NFP', 'Berwyn, IL', 'Berwyn', 'IL', ARRAY['Libraries', 'Advocacy'], 'Library advocacy'),
('Faith Based Nonprofit Resource Center', 'Elkton, MD', 'Elkton', 'MD', ARRAY['Faith', 'Nonprofit Support'], 'Faith-based nonprofit support'),
('The Federated Charities Corporation of Frederick', 'Frederick, MD', 'Frederick', 'MD', ARRAY['Community Development'], 'Community charities'),
('Federation of Neighborhood Centers', 'Philadelphia, PA', 'Philadelphia', 'PA', ARRAY['Community Development'], 'Neighborhood centers'),
('Fideicomiso de Conservación de Puerto Rico', 'San Juan, Puerto Rico', 'San Juan', 'PR', ARRAY['Environment', 'Conservation'], 'Puerto Rico conservation'),
('The Field', 'New York, NY', 'New York', 'NY', ARRAY['Performing Arts', 'Dance'], 'Performing arts support'),
('The Film Collaborative', 'Los Angeles, CA', 'Los Angeles', 'CA', ARRAY['Film'], 'Film distribution'),
('Film Independent', 'Los Angeles, CA', 'Los Angeles', 'CA', ARRAY['Film'], 'Independent film LA'),
('FilmNorth', 'St. Paul MN', 'St. Paul', 'MN', ARRAY['Film'], 'Minnesota film'),
('Filmmakers Collaborative, Inc.', 'Melrose, MA', 'Melrose', 'MA', ARRAY['Film'], 'Filmmaker support'),
('Filmmakers Collaborative SF', 'San Francisco, CA', 'San Francisco', 'CA', ARRAY['Film'], 'SF filmmaker support'),
('Financial Services Coalition — Puget Sound Charitable Foundation', 'Seattle, WA', 'Seattle', 'WA', ARRAY['Financial Services'], 'Financial services'),
('Fiscal Sponsorship Allies Inc.', 'Indianapolis, IN', 'Indianapolis', 'IN', ARRAY['Nonprofit Support'], 'Fiscal sponsorship'),
('FJC', 'New York, NY', 'New York', 'NY', ARRAY['Nonprofit Support', 'Jewish'], 'Jewish philanthropy'),
('The Foraker Group', 'Anchorage, AK', 'Anchorage', 'AK', ARRAY['Nonprofit Support'], 'Alaska nonprofits'),
('Force for Good Community Development Corporation', 'Gary, In', 'Gary', 'IN', ARRAY['Community Development'], 'Community development'),
('Foundation for California Community Colleges', 'Sacramento, CA', 'Sacramento', 'CA', ARRAY['Education'], 'Community college support'),
('Foundation for Independent Artists, Inc. (FIA)', 'New York, NY', 'New York', 'NY', ARRAY['Arts'], 'Independent artists'),
('Foundation for Louisiana', 'Baton Rouge, LA', 'Baton Rouge', 'LA', ARRAY['Community Development'], 'Louisiana communities'),
('Foundation For Montana History', 'Helena, MT', 'Helena', 'MT', ARRAY['History', 'Culture'], 'Montana history'),
('Foundation for the Mid South', 'Jackson, MS', 'Jackson', 'MS', ARRAY['Community Development'], 'Mid South region'),
('Foundation for National Progress', 'San Francisco, CA', 'San Francisco', 'CA', ARRAY['Media', 'Social Justice'], 'Progressive media'),
('Foundry Community Foundation', 'Lincoln, NE', 'Lincoln', 'NE', ARRAY['Community Development'], 'Nebraska community'),
('Fractured Atlas', 'New York, NY', 'New York', 'NY', ARRAY['Arts', 'Culture'], 'Largest arts fiscal sponsor'),
('Fraternal Order of Eagles #3142', 'Chula Vista, CA', 'Chula Vista', 'CA', ARRAY['Community Development'], 'Fraternal organization'),
('Fresh Arts', 'Houston, TX', 'Houston', 'TX', ARRAY['Arts'], 'Houston arts'),
('Friends of the Future', 'Kamuela, HI', 'Kamuela', 'HI', ARRAY['Environment', 'Youth'], 'Hawaii future'),
('Friends of Sacramento Arts', 'Sacramento, CA', 'Sacramento', 'CA', ARRAY['Arts'], 'Sacramento arts'),
('From the Heart Productions', 'Oxnard, CA', 'Oxnard', 'CA', ARRAY['Film'], 'Film production'),
('Fulcrum Arts', 'Pasadena, CA', 'Pasadena', 'CA', ARRAY['Arts'], 'Arts fiscal sponsor'),
('Full Spectrum Features NFP', 'Chicago, IL', 'Chicago', 'IL', ARRAY['Film'], 'Chicago film'),
('Fundación Comunitaria de Puerto Rico', 'San Juan, Puerto Rico', 'San Juan', 'PR', ARRAY['Community Development'], 'Puerto Rico community'),
('Fund for Constitutional Government', 'Washington, D.C.', 'Washington', 'DC', ARRAY['Civic Engagement', 'Democracy'], 'Constitutional government'),
('The Funding Studio', 'Mesa, AZ', 'Mesa', 'AZ', ARRAY['Nonprofit Support'], 'Funding support'),
('Fusion Partnerships, Inc.', 'Baltimore, MD', 'Baltimore', 'MD', ARRAY['Nonprofit Support'], 'Partnership building'),
('Future Earth International', 'Montreal, Quebec, Canada', 'Montreal', 'QC', ARRAY['Environment', 'International'], 'Global sustainability'),
('Give to Africa', 'San Diego, CA', 'San Diego', 'CA', ARRAY['International', 'Africa'], 'African development'),
('Give2Asia', 'San Francisco, CA', 'San Francisco', 'CA', ARRAY['International', 'Asia'], 'Asian philanthropy'),
('Givsum Foundation', 'Newport Beach, CA', 'Newport Beach', 'CA', ARRAY['Community Development'], 'Community giving'),
('The Giving Back Fund', 'Boston, MA', 'Boston', 'MA', ARRAY['Philanthropy'], 'Athlete and celebrity giving'),
('Global Center', 'New York, NY', 'New York', 'NY', ARRAY['International'], 'Global initiatives'),
('Global Fund for Women', 'San Francisco, CA', 'San Francisco', 'CA', ARRAY['Women', 'International'], 'Women\'s rights globally'),
('Global Health Review', 'Venice, CA', 'Venice', 'CA', ARRAY['Health', 'International'], 'Global health'),
('Global Horizons Inc.', 'Minneapolis, MN', 'Minneapolis', 'MN', ARRAY['International'], 'International development'),
('Global Impact', 'Washington D.C.', 'Washington', 'DC', ARRAY['International', 'Philanthropy'], 'International giving'),
('Global Impact Canada', 'Montréal, Canada', 'Montreal', 'QC', ARRAY['International', 'Philanthropy'], 'Canadian international giving'),
('Global Peace Media', 'Ramsey, NJ', 'Ramsey', 'NJ', ARRAY['Media', 'Peace'], 'Peace journalism'),
('GOH Productions', 'New York, NY', 'New York', 'NY', ARRAY['Film', 'Media'], 'Media production'),
('Good Causes, Inc.', 'Albany, NY', 'Albany', 'NY', ARRAY['Community Development'], 'Community support'),
('Goodcity N.F.P.', 'Chicago, IL', 'Chicago', 'IL', ARRAY['Community Development'], 'Chicago community'),
('Goodnation Foundation', 'New York, NY', 'New York', 'NY', ARRAY['Community Development'], 'Community building'),
('The Good Rural', 'San Francisco, CA', 'San Francisco', 'CA', ARRAY['Rural', 'Community Development'], 'Rural communities'),
('The Gotham Center for New York City History', 'New York, NY', 'New York', 'NY', ARRAY['History', 'Culture'], 'NYC history'),
('The Gotham Film & Media Institute', 'New York, NY', 'New York', 'NY', ARRAY['Film'], 'Film education'),
('Grant Assistance Services Inc.', 'Galliano, LA', 'Galliano', 'LA', ARRAY['Nonprofit Support'], 'Grant writing'),
('Grateful Film Fund', 'Santa Monica, CA', 'Santa Monica', 'CA', ARRAY['Film'], 'Film funding'),
('Group 36', 'Philadelphia, PA', 'Philadelphia', 'PA', ARRAY['Social Justice'], 'Social change'),
('GROW', 'Seattle, WA', 'Seattle', 'WA', ARRAY['Community Development'], 'Community growth'),
('The Hack Foundation', 'West Hollywood, CA', 'West Hollywood', 'CA', ARRAY['Youth', 'Education'], 'Youth hacking education'),
('Hacker Fund', 'Santa Monica, CA', 'Santa Monica', 'CA', ARRAY['Tech', 'Education'], 'Tech education'),
('HASER, Inc.', 'San Juan, Puerto Rico', 'San Juan', 'PR', ARRAY['Community Development'], 'Puerto Rico community'),
('Heaven\'s Door Cancer Foundation', 'San Francisco, CA', 'San Francisco', 'CA', ARRAY['Health', 'Cancer'], 'Cancer support'),
('Heffernan Foundation', 'Walnut Creek, CA', 'Walnut Creek', 'CA', ARRAY['Community Development'], 'Community grants'),
('The Hektoen Institute for Medical Research', 'Chicago, IL', 'Chicago', 'IL', ARRAY['Health', 'Research'], 'Medical research'),
('Heluna Health', 'City of Industry, CA', 'City of Industry', 'CA', ARRAY['Health'], 'Public health'),
('Holistic Underground Inc.', 'Oakland, CA', 'Oakland', 'CA', ARRAY['Wellness', 'BIPOC'], 'BIPOC wellness'),
('Hope Across Borders', 'Cheyenne, WY', 'Cheyenne', 'WY', ARRAY['International'], 'Border issues'),
('Houston Cinema Arts Society', 'Houston, TX', 'Houston', 'TX', ARRAY['Film', 'Arts'], 'Houston cinema'),
('Hudson County Latino Foundation', 'Jersey City, N.J.', 'Jersey City', 'NJ', ARRAY['Latino', 'Community Development'], 'Latino community'),
('Humanitarian Social Innovations', 'Bethlehem, PA', 'Bethlehem', 'PA', ARRAY['Social Innovation'], 'Social innovation'),
('Humanity Pathways Global', 'Detroit, MI', 'Detroit', 'MI', ARRAY['International'], 'Global pathways'),
('Image Essays', 'Houston, TX', 'Houston', 'TX', ARRAY['Photography', 'Arts'], 'Photography'),
('Impact Philanthropy Group', 'Riverside, CA', 'Riverside', 'CA', ARRAY['Philanthropy'], 'Impact giving'),
('Independent Arts and Media', 'San Francisco, CA', 'San Francisco', 'CA', ARRAY['Arts', 'Media'], 'Independent media'),
('Independent Pictures', 'Cleveland, OH', 'Cleveland', 'OH', ARRAY['Film'], 'Independent film'),
('Ink People Inc.', 'Eureka, CA', 'Eureka', 'CA', ARRAY['Arts'], 'Arts support'),
('Inquiring Systems, Inc.', 'Sonoma , CA', 'Sonoma', 'CA', ARRAY['Education', 'Research', 'Tech'], 'STEM education and research'),
('Inside and Out Project', 'Casa Grande, AZ', 'Casa Grande', 'AZ', ARRAY['Community Development'], 'Community projects'),
('Institute for Education, Research, and Scholarships', 'Los Angeles, CA', 'Los Angeles', 'CA', ARRAY['Education', 'Research'], 'Education research'),
('Institute for Nonprofit News', 'Los Angeles, CA', 'Los Angeles', 'CA', ARRAY['Media', 'Journalism'], 'Nonprofit journalism'),
('InterMusic SF', 'San Francisco, CA', 'San Francisco', 'CA', ARRAY['Music', 'Arts'], 'Music programs'),
('The International Association of Blacks in Dance, Inc.', 'Silver Spring, MD', 'Silver Spring', 'MD', ARRAY['Dance', 'BIPOC'], 'Black dance'),
('International Documentary Association', 'Los Angeles, CA', 'Los Angeles', 'CA', ARRAY['Film', 'Documentary'], 'Documentary filmmakers'),
('International Friendship Through the Performing Arts', 'Eagan, MN', 'Eagan', 'MN', ARRAY['Performing Arts', 'International'], 'International performing arts'),
('International Information Policy Foundation, Inc.', 'New York, NY', 'New York', 'NY', ARRAY['Tech', 'Policy'], 'Information policy'),
('The Interreligious Foundation for Community Organization', 'New York, NY', 'New York', 'NY', ARRAY['Faith', 'Community Development'], 'Interfaith organizing'),
('Intersection for the Arts', 'San Francisco, CA', 'San Francisco', 'CA', ARRAY['Arts', 'Social Justice', 'BIPOC'], 'BIPOC artists'),
('Jewish Creativity International', 'New York, NY', 'New York', 'NY', ARRAY['Arts', 'Jewish', 'Culture'], 'Jewish arts'),
('Jumpstart Labs', 'Santa Monica, CA', 'Santa Monica', 'CA', ARRAY['Tech', 'Education'], 'Tech education'),
('Kidz Success, Inc.', 'Sacramento, CA', 'Sacramento', 'CA', ARRAY['Youth', 'Education'], 'Youth success'),
('KlezCalifornia', 'El Cerrito, CA', 'El Cerrito', 'CA', ARRAY['Music', 'Jewish', 'Culture'], 'Klezmer music'),
('Ladies In Transit Holistic Community Development Corporation', 'Riverside, NJ', 'Riverside', 'NJ', ARRAY['Women', 'Community Development'], 'Women community development'),
('Local Color', 'San Jose, CA', 'San Jose', 'CA', ARRAY['Arts'], 'Local arts'),
('Local Media Foundation', 'Lake City, MI', 'Lake City', 'MI', ARRAY['Media'], 'Local media'),
('Lokahi Pacific', 'Wailuku, HI', 'Wailuku', 'HI', ARRAY['Pacific Islander', 'Community Development'], 'Pacific Islander community'),
('Los Altos Mountain View Community Foundation', 'Los Altos, CA', 'Los Altos', 'CA', ARRAY['Community Development'], 'Community foundation'),
('Love Foundation', 'Chicago, IL', 'Chicago', 'IL', ARRAY['Community Development'], 'Community love'),
('March On Foundation', 'Annapolis, MD', 'Annapolis', 'MD', ARRAY['LGBTQ+', 'Social Justice'], 'LGBTQ+ advocacy'),
('Marcus Foster Education Institute', 'Oakland, CA', 'Oakland', 'CA', ARRAY['Education'], 'Education equity'),
('MarinLink', 'San Rafael, CA', 'San Rafael', 'CA', ARRAY['Nonprofit Support'], 'Marin nonprofits'),
('The Marion Institute', 'Marion, MA', 'Marion', 'MA', ARRAY['Community Development'], 'Community initiatives'),
('Mayan Spring Inc.', 'Queens, NY', 'Queens', 'NY', ARRAY['Immigration', 'Community Development'], 'Immigrant support'),
('Maysles Documentary Center', 'Harlem, NY 10027', 'New York', 'NY', ARRAY['Film', 'Documentary'], 'Documentary center'),
('Media Alliance', 'San Francisco, CA', 'San Francisco', 'CA', ARRAY['Media'], 'Media advocacy'),
('Media Arts Center San Diego', 'San Diego, CA', 'San Diego', 'CA', ARRAY['Media', 'Arts'], 'Media arts'),
('Midwest Artist Project Services (MAPS)', 'St. Louis, MO', 'St. Louis', 'MO', ARRAY['Arts'], 'Midwest artists'),
('Milwaukee, Film', 'Milwaukee, WI', 'Milwaukee', 'WI', ARRAY['Film'], 'Milwaukee film'),
('Minnesota Fringe Festival', 'Minneapolis, MN', 'Minneapolis', 'MN', ARRAY['Performing Arts'], 'Fringe festival'),
('Ministry Movement', 'Pensacola, FL', 'Pensacola', 'FL', ARRAY['Faith'], 'Ministry support'),
('Mission Earth', 'Framingham, MA', 'Framingham', 'MA', ARRAY['Environment'], 'Environmental mission'),
('Mission Edge', 'San Diego, CA', 'San Diego', 'CA', ARRAY['Nonprofit Support'], 'Nonprofit consulting'),
('Mockingbird Incubator', 'Los Angeles, CA', 'Los Angeles', 'CA', ARRAY['Social Impact'], 'Social enterprise'),
('Mountain Communities Supporting Education Inc., dba The Collective', 'Londonderry, VT', 'Londonderry', 'VT', ARRAY['Education'], 'Rural education'),
('Movement Strategy Center', 'Oakland, CA', 'Oakland', 'CA', ARRAY['Social Justice'], 'Movement building'),
('Multicultural Self-Esteem Academy', 'Houston, TX', 'Houston', 'TX', ARRAY['Youth', 'Multicultural'], 'Youth self-esteem'),
('Multiplier', 'Oakland, CA', 'Oakland', 'CA', ARRAY['Nonprofit Support'], 'Fiscal sponsorship'),
('Myriad USA', 'New York City, NY', 'New York', 'NY', ARRAY['Community Development'], 'Community support'),
('The Narrative Project', 'Houston, TX', 'Houston', 'TX', ARRAY['Storytelling', 'Arts'], 'Narrative arts'),
('National Center for Jewish Film', 'Waltham, MA', 'Waltham', 'MA', ARRAY['Film', 'Jewish', 'Culture'], 'Jewish film'),
('National Center for Reason and Justice', 'Roxbury, MA', 'Roxbury', 'MA', ARRAY['Justice'], 'Justice advocacy'),
('National Network of Public Health Institutes', 'New Orleans, LA', 'New Orleans', 'LA', ARRAY['Health'], 'Public health'),
('National Performance Network', 'New Orleans, LA', 'New Orleans', 'LA', ARRAY['Performing Arts'], 'Performance network'),
('NEO Philanthropy', 'New York, NY', 'New York', 'NY', ARRAY['Philanthropy', 'Social Justice'], 'Progressive philanthropy'),
('Netroots Foundation', 'San Francisco, CA', 'San Francisco', 'CA', ARRAY['Civic Engagement', 'Tech'], 'Online activism'),
('Nevada County Arts Council', 'Nevada City, CA', 'Nevada City', 'CA', ARRAY['Arts'], 'County arts'),
('New Horizons Foundation Inc.', 'Colorado Springs, CO', 'Colorado Springs', 'CO', ARRAY['Community Development'], 'Community support'),
('New Mexico Foundation', 'Santa Fe, NM', 'Santa Fe', 'NM', ARRAY['Community Development'], 'New Mexico community'),
('New Mexico Dance Coalition', 'Santa Fe, NM', 'Santa Fe', 'NM', ARRAY['Dance'], 'New Mexico dance'),
('New Mexico Film Foundation', 'Santa Fe, NM', 'Santa Fe', 'NM', ARRAY['Film'], 'New Mexico film'),
('New Mexico Spotlight Foundation', 'Albuquerque, NM', 'Albuquerque', 'NM', ARRAY['Media', 'Journalism'], 'New Mexico journalism'),
('New Sun Rising', 'Pittsburgh, PA', 'Pittsburgh', 'PA', ARRAY['Community Development'], 'Community renewal'),
('New York Foundation for the Arts', 'New York, NY', 'New York', 'NY', ARRAY['Arts'], 'NY artist support'),
('New York Live Arts', 'New York, NY', 'New York', 'NY', ARRAY['Performing Arts', 'Dance'], 'Contemporary dance'),
('New York Women in Film & Television', 'New York, NY', 'New York', 'NY', ARRAY['Film', 'Women'], 'Women in film'),
('Non Profit Accounting Service', 'Columbia, CA', 'Columbia', 'CA', ARRAY['Nonprofit Support'], 'Nonprofit accounting'),
('Nonprofit Center of the Berkshires, Inc.', 'Great Barrington, MA', 'Great Barrington', 'MA', ARRAY['Nonprofit Support'], 'Berkshires nonprofits'),
('Nonprofit Enterprise at Work, Inc.', 'Ann Arbor, MI', 'Ann Arbor', 'MI', ARRAY['Nonprofit Support'], 'Michigan nonprofits'),
('Nonprofit Organization for Philanthropic Initiatives (NOPI)', 'Norwood, MA', 'Norwood', 'MA', ARRAY['Philanthropy'], 'Philanthropic initiatives'),
('North Dakota Community Foundation', 'Bismarck, ND', 'Bismarck', 'ND', ARRAY['Community Development'], 'North Dakota community'),
('North Kohala Community Resource Center', 'Hawaii, HI', 'Hawaii', 'HI', ARRAY['Community Development'], 'Hawaii community'),
('North Star Community Foundation', 'Fairbanks, AK', 'Fairbanks', 'AK', ARRAY['Community Development'], 'Alaska community'),
('North Woodward Community Foundation', 'Troy, MI', 'Troy', 'MI', ARRAY['Community Development'], 'Michigan community'),
('Northwest Alliance for Alternative Media and Education', 'Portland, OR', 'Portland', 'OR', ARRAY['Media', 'Education'], 'Alternative media'),
('Northwest Film Forum', 'Seattle, WA', 'Seattle', 'WA', ARRAY['Film'], 'Seattle film'),
('NotYetPro', 'Washington, D.C.', 'Washington', 'DC', ARRAY['Nonprofit Support'], 'Emerging nonprofits'),
('Oakland Parks and Recreation Foundation', 'Oakland, CA', 'Oakland', 'CA', ARRAY['Parks', 'Recreation'], 'Oakland parks'),
('Oakland Public Education Fund', 'Oakland, CA', 'Oakland', 'CA', ARRAY['Education'], 'Oakland schools'),
('Obasi Foundation, Inc.', 'Reisterstown, MD', 'Reisterstown', 'MD', ARRAY['Community Development'], 'Community support'),
('Omprakash', 'Seattle, WA', 'Seattle', 'WA', ARRAY['International', 'Youth'], 'Global service learning'),
('On Da Verg', 'Ft. Worth, TX', 'Fort Worth', 'TX', ARRAY['Community Development'], 'Community empowerment'),
('On It Foundation', 'Miami, FL', 'Miami', 'FL', ARRAY['Community Development'], 'Community action'),
('OneOC', 'Santa Ana, CA', 'Santa Ana', 'CA', ARRAY['Nonprofit Support'], 'Orange County nonprofits'),
('On Sacred Ground Land Trust', 'Friday Harbor, WA', 'Friday Harbor', 'WA', ARRAY['Environment', 'Land Conservation'], 'Land trust'),
('OOPS MN', 'Lakeville, MN', 'Lakeville', 'MN', ARRAY['Community Development'], 'Minnesota community'),
('Open Media Foundation', 'Denver, CO', 'Denver', 'CO', ARRAY['Media'], 'Open media'),
('Open Space Institute Inc.', 'New York, NY', 'New York', 'NY', ARRAY['Environment', 'Conservation'], 'Land conservation'),
('Operation Restoration', 'New Orleans, LA', 'New Orleans', 'LA', ARRAY['Community Development'], 'Community restoration'),
('Oregon Wildlife Foundation', 'Portland, OR', 'Portland', 'OR', ARRAY['Wildlife', 'Conservation'], 'Oregon wildlife'),
('Ozcat Entertainment', 'Vallejo, CA', 'Vallejo', 'CA', ARRAY['Film', 'Entertainment'], 'Entertainment'),
('Pacifica\'s Environmental Family', 'Pacifica, CA', 'Pacifica', 'CA', ARRAY['Environment'], 'Environmental family'),
('Pact Donation Collective Inc.', 'Brooklyn, N.Y.', 'Brooklyn', 'NY', ARRAY['Philanthropy'], 'Collective giving'),
('Palms for Life Fund', 'New York, NY', 'New York', 'NY', ARRAY['Community Development'], 'Community fund'),
('PAM CUT', 'Portland, OR', 'Portland', 'OR', ARRAY['Arts'], 'Portland arts'),
('Pan Left Productions', 'Tucson, AZ', 'Tucson', 'AZ', ARRAY['Film'], 'Film production'),
('Panorama Global', 'Seattle, WA', 'Seattle', 'WA', ARRAY['International'], 'Global panorama'),
('Paramount Personalized Learning, Inc.', 'Grand Prairie, TX', 'Grand Prairie', 'TX', ARRAY['Education'], 'Personalized learning'),
('Partners of Parks', 'Long Beach, CA', 'Long Beach', 'CA', ARRAY['Parks'], 'Parks support'),
('Peace Development Fund', 'San Francisco, CA', 'San Francisco', 'CA', ARRAY['Peace', 'Social Justice'], 'Peace and justice'),
('Pecan Street Inc.', 'Austin, TX', 'Austin', 'TX', ARRAY['Energy', 'Sustainability'], 'Energy research'),
('Pensacola Community Action Network, Inc.', 'Pensacola, Fla.', 'Pensacola', 'FL', ARRAY['Community Development'], 'Community action'),
('People In Partnership', 'Charleston, SC', 'Charleston', 'SC', ARRAY['Community Development'], 'Partnership building'),
('Petya I. Edwards Foundation', 'Dallas, TX', 'Dallas', 'TX', ARRAY['Community Development'], 'Community grants'),
('Pittsburgh Filmmakers/Pittsburgh Center for the Arts', 'Pittsburgh, PA', 'Pittsburgh', 'PA', ARRAY['Film', 'Arts'], 'Pittsburgh film and arts'),
('Players Philanthropy Fund', 'Towson, MD', 'Towson', 'MD', ARRAY['Sports', 'Youth', 'Health'], 'Athlete-founded philanthropy'),
('POISE Foundation', 'Pittsburgh, PA', 'Pittsburgh', 'PA', ARRAY['Community Development'], 'Community poise'),
('Praxis Project', 'Oakland, CA', 'Oakland', 'CA', ARRAY['Health', 'Social Justice'], 'Health equity'),
('Preservation Alliance of Minnesota', 'St. Paul, MN', 'St. Paul', 'MN', ARRAY['Historic Preservation'], 'Historic preservation'),
('Progressives Educating New Yorkers, Inc.', 'New York, NY', 'New York', 'NY', ARRAY['Civic Engagement', 'Education'], 'Progressive education'),
('Project Full Out', 'Charlotte, NC', 'Charlotte', 'NC', ARRAY['Community Development'], 'Community projects'),
('Propel Nonprofits', 'Minneapolis, MN', 'Minneapolis', 'MN', ARRAY['Nonprofit Support'], 'Nonprofit capacity'),
('Provincetown Community Compact', 'Provincetown, MA', 'Provincetown', 'MA', ARRAY['Community Development'], 'Community compact'),
('Prudence Helping Hands Foundation', 'Morrisville, NC', 'Morrisville', 'NC', ARRAY['Community Development'], 'Helping hands'),
('Public Health Institute', 'Oakland, CA', 'Oakland', 'CA', ARRAY['Health'], 'Public health'),
('Public Health Institute of Metropolitan Chicago', 'Chicago, IL', 'Chicago', 'IL', ARRAY['Health'], 'Chicago public health'),
('Public Health Solutions', 'New York, NY', 'New York', 'NY', ARRAY['Health'], 'Health solutions'),
('Public Media Inc.', 'New York, NY', 'New York', 'NY', ARRAY['Media'], 'Public media'),
('RVC Seattle', 'Seattle, WA', 'Seattle', 'WA', ARRAY['Community Development'], 'Seattle community'),
('The Redford Center', 'San Francisco, CA', 'San Francisco', 'CA', ARRAY['Film', 'Environment'], 'Environmental storytelling'),
('Reel Hope', 'Atlanta, GA', 'Atlanta', 'GA', ARRAY['Film'], 'Film hope'),
('Resilience Partners NFP', 'Chicago, IL', 'Chicago', 'IL', ARRAY['Community Development'], 'Community resilience'),
('Resources for Human Development', 'Philadelphia, PA', 'Philadelphia', 'PA', ARRAY['Social Services'], 'Human development'),
('Rethink Charity', 'Mineral, VA', 'Mineral', 'VA', ARRAY['Philanthropy'], 'Effective altruism'),
('Rio Grande Community Development Corporation', 'Albuquerque, NM', 'Albuquerque', 'NM', ARRAY['Community Development'], 'Southwest community'),
('Road to Artdom Foundation, Inc.', 'Los Angeles, CA', 'Los Angeles', 'CA', ARRAY['Arts'], 'Arts pathway'),
('Rockefeller Philanthropy Advisors', 'New York, NY', 'New York', 'NY', ARRAY['Philanthropy'], 'Major philanthropy advisor'),
('Rose Foundation for Communities and the Environment', 'Oakland, CA', 'Oakland', 'CA', ARRAY['Environment', 'Community Development'], 'Environmental justice'),
('Russian Riverkeeper', 'Healdsburg, CA', 'Healdsburg', 'CA', ARRAY['Environment', 'Water'], 'River protection'),
('San Francisco Beautiful', 'San Francisco, CA', 'San Francisco', 'CA', ARRAY['Environment', 'Urban'], 'SF beautification'),
('San Francisco Early Music Society', 'Berkeley, CA', 'Berkeley', 'CA', ARRAY['Music', 'Arts'], 'Early music'),
('San Francisco Public Health Foundation', 'San Francisco, CA', 'San Francisco', 'CA', ARRAY['Health'], 'SF public health'),
('San Francisco Study Center', 'San Francisco, CA', 'San Francisco', 'CA', ARRAY['Nonprofit Support'], 'Fiscal Sponsor Directory host'),
('San Juan Resource Conservation & Development Council', 'Durango, CO', 'Durango', 'CO', ARRAY['Environment', 'Conservation'], 'Resource conservation'),
('Santa Barbara Dance Alliance', 'Santa Barbara, CA', 'Santa Barbara', 'CA', ARRAY['Dance'], 'Santa Barbara dance'),
('Sarah Webster Fabio Center for Social Justice', 'Richmond, CA', 'Richmond', 'CA', ARRAY['Social Justice'], 'Social justice center'),
('Satellite Collective ORBIT', 'Rockaway Park, NY', 'Rockaway Park', 'NY', ARRAY['Arts'], 'Arts collective'),
('Schools without Borders', 'Toronto, ON, Canada', 'Toronto', 'ON', ARRAY['Education', 'International'], 'International education'),
('Seattle Parks Foundation', 'Seattle, WA', 'Seattle', 'WA', ARRAY['Parks'], 'Seattle parks'),
('Service After Service', 'Alpharetta, GA', 'Alpharetta', 'GA', ARRAY['Veterans'], 'Veteran support'),
('Service Dogs of Florida, Inc.', 'Winter Garden, FL', 'Winter Garden', 'FL', ARRAY['Disability', 'Animals'], 'Service dogs'),
('SE Uplift Neighborhood Coalition', 'Portland, OR', 'Portland', 'OR', ARRAY['Community Development'], 'Portland neighborhoods'),
('Seventh Generation Fund for Indian Development', 'Arcata, CA', 'Arcata', 'CA', ARRAY['Indigenous', 'Native American'], 'Native American development'),
('Shunpike', 'Seattle, WA', 'Seattle', 'WA', ARRAY['Arts'], 'Seattle arts fiscal sponsor'),
('Side Project Inc.', 'West Palm Beach, FL', 'West Palm Beach', 'FL', ARRAY['Community Development'], 'Side projects'),
('Silent Hall of Fame', 'Moraga, CA', 'Moraga', 'CA', ARRAY['Film', 'History'], 'Silent film history'),
('SIMA Studios', 'West Hollywood, CA', 'West Hollywood', 'CA', ARRAY['Film'], 'Film studios'),
('Siskiyou County Arts Council', 'Mount Shasta, CA', 'Mount Shasta', 'CA', ARRAY['Arts'], 'County arts'),
('Social & Environmental Entrepreneurs', 'Calabasas, CA', 'Calabasas', 'CA', ARRAY['Social Enterprise', 'Environment'], 'Social entrepreneurship'),
('Social Impact Fund', 'Los Angeles, CA', 'Los Angeles', 'CA', ARRAY['Social Impact'], 'Impact projects'),
('SocialGood', 'Oakland, CA', 'Oakland', 'CA', ARRAY['Social Impact'], 'Social good'),
('SOMArts', 'San Francisco, CA', 'San Francisco', 'CA', ARRAY['Arts'], 'SF arts venue'),
('SouthCoast Community Foundation', 'New Bedford, MA', 'New Bedford', 'MA', ARRAY['Community Development'], 'Massachusetts community'),
('Southern Conservation Partners, Inc.', 'Raleigh, NC', 'Raleigh', 'NC', ARRAY['Environment', 'Conservation'], 'Southern conservation'),
('Southern Documentary Fund', 'Durham, NC', 'Durham', 'NC', ARRAY['Film', 'Documentary'], 'Southern documentary'),
('Southern Illinois Community Foundation', 'Marion, IL', 'Marion', 'IL', ARRAY['Community Development'], 'Southern Illinois'),
('Southern Vision Alliance', 'Durham, NC', 'Durham', 'NC', ARRAY['Media', 'Social Justice'], 'Southern storytelling'),
('Southwest Research and Information Center', 'Albuquerque, NM', 'Albuquerque', 'NM', ARRAY['Environment', 'Research'], 'SW research'),
('Southwestern Colorado Area Health Education Center', 'Durango, CO', 'Durango', 'CO', ARRAY['Health', 'Education'], 'Health education'),
('SPM Disability Justice Fund', 'San Francisco, CA', 'San Francisco', 'CA', ARRAY['Disability', 'Social Justice'], 'Disability justice'),
('Springboard for the Arts', 'St. Paul, MN', 'St. Paul', 'MN', ARRAY['Arts'], 'Artist support'),
('Streams in the Desert Foundation, Inc. dba High Desert Community Foundation', 'Apple Valley, CA', 'Apple Valley', 'CA', ARRAY['Community Development'], 'Desert community'),
('Streams of Dreams, Inc.', 'Douglasville, GA', 'Douglasville', 'GA', ARRAY['Community Development'], 'Dream fulfillment'),
('Sustainable Seattle', 'Seattle, WA', 'Seattle', 'WA', ARRAY['Environment', 'Sustainability'], 'Seattle sustainability'),
('Sweet Home Community Foundation', 'Sweet Home, OR', 'Sweet Home', 'OR', ARRAY['Community Development'], 'Oregon community'),
('TCF The Community\'s Foundation', 'Springfield, PA', 'Springfield', 'PA', ARRAY['Community Development'], 'Community foundation'),
('Technical Assistance Partnership of Arizona (TAPAZ)', 'Phoenix, AZ', 'Phoenix', 'AZ', ARRAY['Nonprofit Support'], 'Arizona nonprofits'),
('The Ocean Foundation', 'Washington, D.C.', 'Washington', 'DC', ARRAY['Environment', 'Ocean'], 'Ocean conservation'),
('The Reading Room CLE', 'Cleveland, OH', 'Cleveland', 'OH', ARRAY['Education', 'Literacy'], 'Cleveland literacy'),
('The Resource Foundation', 'New York, NY', 'New York', 'NY', ARRAY['Nonprofit Support'], 'Resource sharing'),
('Theater Resources Unlimited', 'New York, New York', 'New York', 'NY', ARRAY['Theater', 'Performing Arts'], 'Theater resources'),
('#TeenWritersProject', 'Dallas, TX', 'Dallas', 'TX', ARRAY['Writing', 'Youth'], 'Teen writing'),
('Third World Newsreel', 'New York, NY', 'New York', 'NY', ARRAY['Film', 'Social Justice'], 'Third world cinema'),
('Tides Center', 'San Francisco, CA', 'San Francisco', 'CA', ARRAY['Social Justice', 'Environment', 'All Fields'], 'Major fiscal sponsor'),
('Tiny Seed Project Inc.', 'Greensboro Bend, VT', 'Greensboro Bend', 'VT', ARRAY['Community Development'], 'Small projects'),
('TLEEM', 'Round Rock, TX', 'Round Rock', 'TX', ARRAY['Community Development'], 'Community support'),
('Tomorrow\'s Education Network, Inc.', 'Towaco, NJ', 'Towaco', 'NJ', ARRAY['Education'], 'Future education'),
('Trailhead Institute', 'Denver, CO', 'Denver', 'CO', ARRAY['Education', 'Leadership'], 'Leadership development'),
('Transformative Culture Project', 'Roxbury, MA', 'Roxbury', 'MA', ARRAY['Arts', 'Social Justice'], 'Transformative arts'),
('Trees Foundation', 'Redway, CA', 'Redway', 'CA', ARRAY['Environment', 'Forest'], 'Forest protection'),
('Triangle Advising for Nonprofits', 'Toluca Lake, CA', 'Toluca Lake', 'CA', ARRAY['Nonprofit Support'], 'Nonprofit consulting'),
('Triangle ArtWorks', 'Raleigh, NC', 'Raleigh', 'NC', ARRAY['Arts'], 'Triangle arts'),
('TriCounty Community Network', 'Pottstown, PA', 'Pottstown', 'PA', ARRAY['Community Development'], 'Tri-county community'),
('Truckee Meadows Parks Foundation', 'Reno, NV', 'Reno', 'NV', ARRAY['Parks'], 'Nevada parks'),
('TSNE', 'Boston, MA', 'Boston', 'MA', ARRAY['Nonprofit Support'], 'Nonprofit support'),
('Twin Rivers Council for the Arts', 'Mankato, MN', 'Mankato', 'MN', ARRAY['Arts'], 'Regional arts'),
('Unique Projects Inc.', 'New York, NY', 'New York', 'NY', ARRAY['Community Development'], 'Unique projects'),
('United Charitable', 'Ashburn, VA', 'Ashburn', 'VA', ARRAY['Philanthropy'], 'Donor-advised funds'),
('United Way of Southwest Colorado', 'Durango, CO 81302', 'Durango', 'CO', ARRAY['Community Development'], 'United Way'),
('UI Charitable', 'Provo, UT', 'Provo', 'UT', ARRAY['Philanthropy'], 'Charitable giving'),
('Uplift Alliance', 'Baltimore, MD', 'Baltimore', 'MD', ARRAY['Community Development'], 'Baltimore uplift'),
('Urban Affairs Coalition', 'Philadelphia, PA', 'Philadelphia', 'PA', ARRAY['Urban', 'Community Development'], 'Urban affairs'),
('Urban Mediamakers', 'Norcross, GA', 'Norcross', 'GA', ARRAY['Film', 'Media'], 'Urban media'),
('Urban Sustainability Directors Network', 'Sanford, N.C.', 'Sanford', 'NC', ARRAY['Environment', 'Urban'], 'Urban sustainability'),
('Use The News Foundation', 'San Francisco, CA', 'San Francisco', 'CA', ARRAY['Media', 'Education'], 'News literacy'),
('U.S.-Mexico Border Philanthropy Partnership', 'San Diego, CA', 'San Diego', 'CA', ARRAY['International', 'Border'], 'Border philanthropy'),
('Utah Cold Case Coalition', 'Salt Lake City, UT', 'Salt Lake City', 'UT', ARRAY['Justice'], 'Cold cases'),
('Veterans Awareness Transition Corporation', 'Beverly, NJ', 'Beverly', 'NJ', ARRAY['Veterans'], 'Veteran transition'),
('Village Earth', 'Fort Collins, CO', 'Fort Collins', 'CO', ARRAY['International', 'Sustainability'], 'Global sustainability'),
('Visions Made Viable', 'Irvine, CA', 'Irvine', 'CA', ARRAY['Community Development'], 'Vision implementation'),
('VOW Foundation', 'Oswego, NY', 'Oswego', 'NY', ARRAY['Community Development'], 'Community vow'),
('Washington Research Institute', 'Ukiah, CA', 'Ukiah', 'CA', ARRAY['Research'], 'Research institute'),
('The Watershed Project', 'Richmond, CA', 'Richmond', 'CA', ARRAY['Environment', 'Water'], 'Watershed protection'),
('Wave Farm', 'Acra, NY', 'Acra', 'NY', ARRAY['Media', 'Arts'], 'Transmission arts'),
('We Bloom Inc.', 'Indianapolis, IN', 'Indianapolis', 'IN', ARRAY['Community Development'], 'Community bloom'),
('West Contra Costa Public Education Fund', 'Richmond, CA', 'Richmond', 'CA', ARRAY['Education'], 'Education fund'),
('WHOmentorsdotcom Inc.', 'San Jose, CA', 'San Jose', 'CA', ARRAY['Mentorship'], 'Mentorship network'),
('Women in Film & Video', 'Washington, D.C.', 'Washington', 'DC', ARRAY['Film', 'Women'], 'Women in film DC'),
('Women Make Movies', 'New York, NY', 'New York', 'NY', ARRAY['Film', 'Women'], 'Women filmmakers'),
('WoMN ACT® (Advocate, Collaborate, Transform)', 'St. Paul, MN', 'St. Paul', 'MN', ARRAY['Women', 'Community Development'], 'Women action'),
('The Woods Hole Film Festival', 'Woods Hole, MA', 'Woods Hole', 'MA', ARRAY['Film'], 'Film festival'),
('Youth Leadership Incubator dba Hack+', 'Fremont, CA', 'Fremont', 'CA', ARRAY['Youth', 'Leadership'], 'Youth hacking'),
('YWCA of Greater Portland', 'Portland, OR', 'Portland', 'OR', ARRAY['Women', 'Community Development'], 'YWCA Portland')
ON CONFLICT DO NOTHING;
